apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: space-cargo-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mahmoudmetwall2y/DEPI-Graduation-Project-'
    targetRevision: feature/gitops-app-of-apps
    path: infrastructure/argo-apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true