nameOverride: ""
fullnameOverride: ""

namespace:
  create: false
  name: space-cargo

imagePullSecrets: []

global:
  imageRegistry: docker.io/mahmoudmetwall2y
  imagePullPolicy: IfNotPresent

services:
  frontend:
    image: depi-frontend
    tag: ""
    replicas: 2
    port: 8080
    healthPath: /healthz
    serviceAccount: frontend
    runAsUser: 101
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 128Mi
    writableVolumes:
      - name: nginx-cache
        mountPath: /var/cache/nginx
      - name: nginx-run
        mountPath: /var/run
    pdb:
      enabled: true
      minAvailable: 1

  cargo-service:
    image: depi-cargo-service
    tag: ""
    replicas: 1
    port: 8000
    healthPath: /health
    serviceAccount: cargo-service
    runAsUser: 10001
    env:
      TELEMETRY_SERVICE_URL: http://telemetry-service:8000
      ROUTING_SERVICE_URL: http://routing-service:8000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    pdb:
      enabled: false

  telemetry-service:
    image: depi-telemetry-service
    tag: ""
    replicas: 2
    port: 8000
    healthPath: /health
    serviceAccount: telemetry-service
    runAsUser: 10001
    resources:
      requests:
        cpu: 100m
        memory: 96Mi
      limits:
        cpu: "1"
        memory: 256Mi
    pdb:
      enabled: true
      minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilizationPercentage: 65

  routing-service:
    image: depi-routing-service
    tag: ""
    replicas: 2
    port: 8000
    healthPath: /health
    serviceAccount: routing-service
    runAsUser: 10001
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 300m
        memory: 128Mi
    pdb:
      enabled: true
      minAvailable: 1

networkPolicy:
  enabled: true

istio:
  enabled: true
  trustDomain: cluster.local
  gateway:
    name: space-cargo-gateway
  ingressGateway:
    namespace: istio-system
    serviceAccount: istio-ingressgateway
  hosts:
    - "*"
  mtlsMode: STRICT
  authorizationPolicy:
    enabled: true
