{{- range $name, $service := .Values.services }}
{{- if $service.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "space-cargo.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $service.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
{{- end }}
{{- end }}
