{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.serviceAccount }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "space-cargo.labels" $ | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
